[model]
name = "tiny"
max_batch_size = 2
max_seq_len = 1024 
dtype = "bf16"
vocab_size = 102400
dim = 128
inter_dim = 256
moe_inter_dim = 32
n_layers = 2
n_dense_layers = 1
n_heads = 2
n_routed_experts = 2
n_shared_experts = 1
n_activated_experts = 1
n_expert_groups = 1
n_limited_groups = 1
score_func = "softmax"
route_scale = 1.0
q_lora_rank = 0
kv_lora_rank = 16
qk_nope_head_dim = 16
qk_rope_head_dim = 16
v_head_dim = 16
original_seq_len = 1024
rope_theta = 10000.0
rope_factor = 40
beta_fast = 32
beta_slow = 1
mscale = 0.707

[tokenizer]
path = "./asset/cl100k_base.tiktoken"